apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: storybook-amplify-components
spec:
  environments:
    - name: test
      build:
        from: main
    - name: feature
      build:
        from: feature-release/**
    - name: production

  components:
    - name: client
      src: ./
      ports:
        - name: https
          port: 8080
      publicPort: https
      environmentConfig:
        - environment: feature
          horizontalScaling:
            minReplicas: 0
            maxReplicas: 1
      secrets:
        - GITHUB_PAT_SEARCH_TOKEN

  dnsAppAlias:
    environment: production
    component: client
