apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: storybook-amplify-components
spec:
  environments:
    - name: production
      build:
        from: main
    - name: feature
      build:
        from: feature-release/**

  components:
    - name: client
      src: ./
      ports:
        - name: https
          port: 8080
      publicPort: https

  dnsAppAlias:
    environment: production
    component: client
