name: Build docker image
on:
  workflow_call:
jobs:
  build-docker:
    name: Build client docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the docker image
        working-directory: client
        run: docker build . --file Dockerfile
