name: Pull request

on:
  pull_request:
    branches: [main, master, develop, development, staging]
    paths:
      - "client/**"
      - ".github/workflows/**"
  workflow_dispatch:
jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  e2e:
    name: E2E Test
    uses: ./.github/workflows/e2e.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  build-docker:
    name: Build docker image
    uses: ./.github/workflows/build_docker.yaml

  check_configs:
    name: Check Config files
    uses: ./.github/workflows/check_config.yaml

