name: Test
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Unit tests
        working-directory: client
        run: npm run test:ci --passWithNoTests
