name: Lint
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - uses: actions/checkout@v3
      - name: Linting dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
