name: NPM Publish
on:
  workflow_call:
    secrets:
      npm-token:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:ci

      - name: Build Components
        run: npm run build-components:ci

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.npm-token }}
